export const featuredPortfolio = [{
        id: 1,
        title: "The Tabata App",
        img: "../public/PNG/tabata-app.png",
        description: "this is a simple test",
        tech: ["React Native"],
        retex: "link-test",
        githubLink: "www.google.com",
    },
    {
        id: 2,
        title: "Lowatem AI",
        img: "../public/PNG/tabata-app.png",
        description: "this is a simple test",
        tech: ["React Native"],
        retex: "link-test",
        githubLink: "github-link test",
    },
    {
        id: 3,
        title: "Pong",
        img: "../public/PNG/tabata-app.png",
        description: "this is a simple test",
        tech: ["React Native"],
        retex: "link-test",
        githubLink: "github-link test",
    },
    {
        id: 4,
        title: "Clajem",
        img: "../public/PNG/tabata-app.png",
        description: "this is a simple test",
        tech: ["React Native"],
        retex: "link-test",
        githubLink: "github-link test",
    },
];