export const featuredPortfolio = [{
        id: 1,
        title: "The Tabata App",
        img: "../public/PNG/tabata-app.png",
        description: "A simple Tabata application compatible on IOS and Android. My React Native project",
        tech: ["React Native"],
        retex: "link-test",
        githubLink: "www.google.com",
    },
    {
        id: 2,
        title: "Lowatem AI",
        img: "../public/PNG/tabata-app.png",
        description: "Project for the IUT. Board game with two opposing players who must eliminate all the soldiers of the opposing player first. Development of an AI that must beat other players and AI",
        tech: ["Java"],
        retex: "link-test",
        githubLink: "https://github.com/enzo-mourany/ia_lowatem",
    },
    {
        id: 3,
        title: "Pong",
        img: "../public/PNG/tabata-app.png",
        description: "First project for the IUT. Development of the classic pong game with objects, collision, balls and sprites management.",
        tech: ["Java", "Processing"],
        retex: "link-test",
        githubLink: "https://github.com/enzo-mourany/pong-java-iut",
    },
    {
        id: 4,
        title: "Clajem",
        img: "../public/PNG/tabata-app.png",
        description: "Project for the IUT. Creation of an electric skateboard rental and sale business. Realization of the PESTEL analysis and its website. Team project",
        tech: ["HTML", "CSS"],
        retex: "link-test",
        githubLink: "github-link test",
    },
];